VMS=kvm.centos-6.3-i386 kvm.centos-6.3-x86_64 kvm.centos-6.4-i386 kvm.centos-6.4-x86_64 kvm.centos-6.5-i386 kvm.centos-6.5-x86_64 virtualbox.centos-6.3-i386 virtualbox.centos-6.3-x86_64 virtualbox.centos-6.4-x86_64 virtualbox.centos-6.5-i386 virtualbox.centos-6.5-x86_64

all:

kvm.centos-6.3-i386:
	(cd $@ && make)

kvm.centos-6.3-x86_64:
	(cd $@ && make)

kvm.centos-6.4-i386:
	(cd $@ && make)

kvm.centos-6.4-x86_64:
	(cd $@ && make)

kvm.centos-6.5-i386:
	(cd $@ && make)

kvm.centos-6.5-x86_64:
	(cd $@ && make)

virtualbox.centos-6.3-i386:
	(cd $@ && make)

virtualbox.centos-6.3-x86_64:
	(cd $@ && make)

virtualbox.centos-6.4-x86_64:
	(cd $@ && make)

virtualbox.centos-6.5-i386:
	(cd $@ && make)

virtualbox.centos-6.5-x86_64:
	(cd $@ && make)

.PHONY: $(VMS)
